### ISSUE TITLE
Serverless and Dynatrace Integration not working with internal folder structures 

### ISSUE THREAD

**Issue by charanack** [Dynatrace/serverless-oneagent#11]
I am trying to integrate Dynatrace with Serverless Webpack Node 10.x and facing weird issue folder structures.

my current structure is `app/src/handler/handler.ts` file

Cloud formation template for Handler is 
     ` "Handler": "node_modules/@dynatrace/oneagent/index.src/handler/HealthHandler$health",`  

```
{
    "errorType": "Runtime.MalformedHandlerName",
    "errorMessage": "Bad handler",
    "stack": [
        "Runtime.MalformedHandlerName: Bad handler",
        "    at _splitHandlerString (/var/runtime/UserFunction.js:43:11)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:138:31)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
```

if I change my handler to top-level and it's working fine 
Updated structure is `app/handler.ts` file

Cloud formation template for Handler is
 `"Handler": "node_modules/@dynatrace/oneagent/index.HealthHandler$health",`

AWS lambda strictly checks the total path in Node 10.x version. if the path is wrong it will throw an error.
https://gist.github.com/brianleroux/26e4d9795350047c6ae2efcbe57e1291#file-userfunction-js-L40.

Thanks.

**Comment by Hollerberg** [comment]
Unluckily, AWS changed the function handler definition parsing code with the new Node.js runtime. 

In old runtime, split(".") was used to decompose module file part and exported handler part. Now, path.basename is used to decompose handler definition, which will result in above error. There is no quick fix for this other to deploy the handler to the root folder.

I will investigate how to overcome this limitation.

**Comment by charanack** [comment]
@Hollerberg Thanks for looking at this issue. let me know if you need help with testing.

can we change or update serverless webpack.config to generate output js file to root folder irrespective of folder structures and reference to Dynatrace to root?

**Comment by Hollerberg** [comment]
I just published v1.0.11 which should resolve the sub-folder issue. 

Please note, that the fix requires an updated version of @dynatrace/oneagent npm package. Updates have been already published (@dynatrace/oneagent@1.175.270-1.0.1 and @dynatrace/oneagent@1.177.216-1.0.1).

In addition, the update will reduce overall bundle file size. Let me know if things work out for you.

**Comment by charanack** [comment]
**Sub folder issue**
I used latest version of @dynatrace/oneagent@1.175.270-1.0.1  and  "@dynatrace/serverless-oneagent": "^1.0.11" and still facing sub folder issue.

Error
Endpoint response body before transformations: {"errorType":"Runtime.MalformedHandlerName","errorMessage":"Bad handler","trace":["Runtime.MalformedHandlerName: Bad handle

do you have any working example ?

**Buildsize:-**
I see that builid size reduce by 6 MB

Is this new Npm package released  `@dynatrace/oneagent@1.177.216-1.0.1` ?

**Comment by beeme1mr** [comment]
I was running into a similar problem trying to upgrade to 10.x. I've confirmed that I'm running v1.0.11.

`FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
    0x55fdaa5b5203 node::Abort() [/var/lang/bin/node]
    0x55fdaa5b525f [/var/lang/bin/node]
    0x55fdaa7f6f89 v8::Utils::ReportApiFailure(char const*, char const*) [/var/lang/bin/node]
    0x7fe73eabd56d [/var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-64/oneagentnode_64.node]
    0x7fe73eabc405 [/var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-64/oneagentnode_64.node]
    0x55fdaadabfb8 v8::internal::PropertyCallbackArguments::CallNamedGetter(v8::internal::Handle<v8::internal::InterceptorInfo>, v8::internal::Handle<v8::internal::Name>) [/var/lang/bin/node]
    0x55fdaadaddbb [/var/lang/bin/node]
    0x55fdaadde9c7 v8::internal::Object::GetProperty(v8::internal::LookupIterator*) [/var/lang/bin/node]
    0x55fdaad09ae4 v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/var/lang/bin/node]
    0x55fdaad09f7c v8::internal::KeyedLoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/var/lang/bin/node]
    0x55fdaad0a60b v8::internal::Runtime_KeyedLoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/var/lang/bin/node]
    0x2197f465be1d `

Removing the OneAgent plugin from the Serverless config resolves the issue.

**Comment by Hollerberg** [comment]
@charanack,

I found an issue in the 1.0.11. The plugin fail to add the environment variable DT_LAMBDA_HANDLER to the functions. This environment variable is needed by @dynatrace/oneagent at function runtime to require the user Lambda function.
Unluckily, this issue did not show up during my tests, as the serverless.yml files in my test project included a manually added DT_LAMBDA_HANDLER environment variable. 
This is a sample project with functions in subfolder: https://github.com/Hollerberg/serverless-oneagent-sample. 

Both @latest (@dynatrace/oneagent@1.175.270-1.0.1) and @next (@dynatrace/oneagent@1.177.216-1.0.1) have been updated accordingly.

Sorry for the inconvenience!

**Comment by charanack** [comment]
@Hollerberg I am still facing the same issue. I try to debug issue 

which code part enable this line ?
`const setDtLambdaHandler = this.options["dt-set-dt-lambda-handler"] || ymlConfig.setDtLambdaHandler;`
my handle not executing if statment.
https://github.com/Dynatrace/serverless-oneagent/commit/e7c4e3f4d626c216b76e93ead095541608c33d66#diff-f41e9d04a45c83f3b6f6e630f10117feR323
https://github.com/Dynatrace/serverless-oneagent/commit/e7c4e3f4d626c216b76e93ead095541608c33d66#diff-f41e9d04a45c83f3b6f6e630f10117feR540

do I need to set a `DT_LAMBDA_HANDLER`?

**Comment by Hollerberg** [comment]
Could you execute ```SLS_DEBUG=\* serverless package --verbose``` and post the console output? 

DT_LAMBDA_HANDLER will be set automatically if @dynatrace/oneagent supports that feature (which is the case for e.g. @dynatrace/oneagent@1.175.270-1.0.1 and @dynatrace/oneagent@1.177.216-1.0.1). 

The quoted code checks, if command line option --dt-set-dt-lambda-handler or serverless.yml setting setDtLambdaHandler are set. These settings can be used to override the automatic detection of DT_LAMBDA_HANDLER support in @dynatrace/oneagent and should only be required in troubleshooting scenarios (e.g. to disable DT_LAMBDA_HANDLER feature).

If the options are not defined, the code in the else branch will enable DT_LAMBDA_HANDLER dependent on the determination if @dynatrace/oneagent supports that feature.
```
this.config.setDtLambdaHandler = this.config.oneagentNpmModuleSupportsDtLambdaHandler;
```

**Comment by beeme1mr** [comment]
My issue was resolved by the latest update.

**Comment by charanack** [comment]
@Hollerberg  added console output. as mentioned in my previous comment newly added code is not executing 	`this.log(`adding DT_LAMBDA_HANDLER=${origHandler}`);`

This is my repo. am I missing anything in the serverless. yml file. this is npm based project
https://github.com/CharanRoot/Dynatrace_AWS_Serverless

**SLS_DEBUG=\* serverless package --verbose**
```
$ SLS_DEBUG=\* serverless package --verbose
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: [Dynatrace OneAgent] switching to 'Webpack' mode
Serverless: [Dynatrace OneAgent] installing listener for 'before:package:createDeploymentArtifacts' in context of PlainServerless
Serverless: [Dynatrace OneAgent] installing listener for 'after:package:createDeploymentArtifacts' in context of PlainServerless
Serverless: [Dynatrace OneAgent] installing listener for 'before:package:initialize' in context of Webpack
Serverless: [Dynatrace OneAgent] installing listener for 'after:webpack:package:packExternalModules' in context of Webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: [AWS ssm 200 0.345s 0 retries] getParameter({ Name: '/dynatrace/lambda/DT_LAMBDA_OPTIONS',
  WithDecryption: true })
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: [Dynatrace OneAgent] noop in event 'aws:common:validate:validate'
Serverless: Invoke aws:common:cleanupTempDir
Serverless: [Dynatrace OneAgent] noop in event 'aws:common:cleanupTempDir:cleanup'
Serverless: [Dynatrace OneAgent] noop in event 'package:cleanup'
Serverless: [Dynatrace OneAgent] executing event 'before:package:initialize'
Serverless: [Dynatrace OneAgent] adding @dynatrace/oneagent to virgin forceInclude
Serverless: [Dynatrace OneAgent] adding environment variable DT_LAMBDA_OPTIONS='redacted'
Serverless: [Dynatrace OneAgent] noop in event 'package:initialize'
Serverless: [Dynatrace OneAgent] noop in event 'package:setupProviderConfiguration'
Serverless: Invoke webpack:validate
Serverless: Using configuration:
{
  "includeModules": {
    "forceInclude": [
      "@dynatrace/oneagent"
    ]
  },
  "webpackConfig": "webpack.config.js",
  "packager": "npm",
  "packagerOptions": {},
  "keepOutputDirectory": false
}
Serverless: Removing /Users/username/job-experience/dyantrace_test/.webpack
Serverless: Using multi-compile (individual packaging)
Serverless: [Dynatrace OneAgent] noop in event 'webpack:validate:validate'
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 96ms
Built at: 10/28/2019 4:07:36 PM
         Asset      Size  Chunks             Chunk Names
hello/index.js  1.38 KiB       0  [emitted]  hello/index
Entrypoint hello/index = hello/index.js
[0] ./hello/index.js 212 bytes {0} [built]
[1] ./node_modules/left-pad/index.js 1.43 KiB {0} [built]
Serverless: [Dynatrace OneAgent] noop in event 'webpack:compile:compile'
Serverless: Invoke webpack:package
Serverless: Fetch dependency graph from /Users/username/job-experience/dyantrace_test/package.json
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: @dynatrace/oneagent@^1.175.270-1.0.1
Serverless: Package took [5282 ms]
Serverless: Copy modules: /Users/username/job-experience/dyantrace_test/.webpack/hello [467 ms]
Serverless: Prune: /Users/username/job-experience/dyantrace_test/.webpack/hello [1172 ms]
Serverless: Run scripts: /Users/username/job-experience/dyantrace_test/.webpack/hello [0 ms]
Serverless: [Dynatrace OneAgent] noop in event 'webpack:package:packExternalModules'
Serverless: [Dynatrace OneAgent] executing event 'after:webpack:package:packExternalModules'
Serverless: [Dynatrace OneAgent] tailoring OneAgent module in /Users/username/job-experience/dyantrace_test/.webpack/hello
Serverless: [Dynatrace OneAgent] executing /Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/.bin/dt-oneagent-tailor --AwsLambdaV10
Serverless: [Dynatrace OneAgent] Tailoring npm module for environment 'AWS Lambda with Node 10.x'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-32/oneagentnode_48.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-32/oneagentnode_57.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-64/oneagentnode_48.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-64/oneagentnode_57.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-64/oneagentnode_67.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.175.270.20190920-173335/linux-x86-64/oneagentnode_72.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/any/onenodeloader.js'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-32/liboneagentloader.so'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-32/oneagentnodeloader_48.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-32/oneagentnodeloader_57.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-64/liboneagentloader.so'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-64/oneagentnodeloader_48.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-64/oneagentnodeloader_57.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-64/oneagentnodeloader_64.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-64/oneagentnodeloader_67.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/bin/linux-x86-64/oneagentnodeloader_72.node'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/lib/liboneagentproc.so'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/lib/oneagentdumpproc'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/lib64/liboneagentproc.so'
Serverless: [Dynatrace OneAgent]   deleting file '/Users/username/job-experience/dyantrace_test/.webpack/hello/node_modules/@dynatrace/oneagent-dependency/agent/lib64/oneagentdumpproc'
Serverless: [Dynatrace OneAgent] Tailoring npm module for environment 'AWS Lambda with Node 10.x': SUCCEEDED
Serverless: [Dynatrace OneAgent] tailoring OneAgent module succeeded
Serverless: [Dynatrace OneAgent] function hello runtime is nodejs10.x
Serverless: [Dynatrace OneAgent] modifying Lambda handler hello: hello/index.hello -> node_modules/@dynatrace/oneagent/index.hello/index$hello
Serverless: Zip function: /Users/username/job-experience/dyantrace_test/.webpack/hello [1196 ms]
Serverless: [Dynatrace OneAgent] noop in event 'webpack:package:packageModules'
Serverless: Packaging service...
Serverless: [Dynatrace OneAgent] noop in event 'package:createDeploymentArtifacts'
Serverless: Remove /Users/username/job-experience/dyantrace_test/.webpack
Serverless: [Dynatrace OneAgent] noop in event 'before:package:compileLayers'
Serverless: [Dynatrace OneAgent] noop in event 'package:compileLayers'
Serverless: [Dynatrace OneAgent] noop in event 'before:package:compileFunctions'
Serverless: [Dynatrace OneAgent] noop in event 'package:compileFunctions'
Serverless: [Dynatrace OneAgent] noop in event 'package:compileEvents'
Serverless: Invoke aws:package:finalize
Serverless: [Dynatrace OneAgent] noop in event 'aws:package:finalize:mergeCustomProviderResources'
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: [Dynatrace OneAgent] noop in event 'aws:common:moveArtifactsToPackage:move'
Serverless: [Dynatrace OneAgent] noop in event 'aws:package:finalize:saveServiceState'
Serverless: [Dynatrace OneAgent] noop in event 'package:finalize'
Serverless: [Dynatrace OneAgent] noop in event 'after:package:finalize'
```

**Comment by Hollerberg** [comment]
I published v1.0.13 with a fix for webpack deployment.

**Comment by Hollerberg** [comment]
@charanack - is my interpretation of the emoji correct and the issue can be closed? If so, thanks for your patience and perpetual help - and sorry for the lengthy resolution.

**Comment by charanack** [comment]
@Hollerberg it's working Thanks for your help. Do you have any timeline for node_module optimization and minification?

**Comment by Hollerberg** [comment]
closing - to my knowledge, the open question about timeline has been addressed already in alternative channels.
