### ISSUE TITLE
Data from Lambda not reaching Dynatrace

### ISSUE THREAD

**Issue by mcsmcs** [Dynatrace/serverless-oneagent#6]
After implementing the serverless-oneagent plugin and deploying the data never shows up in the Dynatrace UI.  Upon looking at the lambda logs the following warning is present

```
2019-01-08 00:28:41.633 UTC [6b4d089f] info [native] Server/Collector ............ http://localhost:8020/communication
2019-01-08 00:28:41.634 UTC [6b4d089f] info [native] URL http://localhost:8020/communication not working (Failed to connect to localhost port 8020: Connection refused)
```

It looks like the plugin isn't picking up the `server` value that we're providing via the DT_LAMBDA_OPTIONS.

I've tried a few variations of providing the options but all had the same result (localhost):

- SSM with SecureString in custom/serverless-oneagent/options
- SSM in Environment Variables ([like this](https://www.dynatrace.com/news/blog/deploying-your-lambda-function-and-dynatrace-in-8-minutes/))
- sls deploy with --dt-options
- Hard-coded in serverless.yml in custom/serverless-oneagent/options

Currently using versions:
- "@dynatrace/oneagent": "1.157.186-1.0.0",
- "@dynatrace/serverless-oneagent": "1.0.5"

**Comment by Hollerberg** [comment]
Could you provide the full agent log file? I am especially interested in the log lines like

> info [nodejs] Agent options: { dynatraceTagPropertyPath: 'headers.x-dynatrace', server: 'https://xyz.xyz.com', tenant: 'XYZ, tenanttoken: 'XYZ' }

and 

>info [native] Environment ................. "DT_LAMBDA_OPTIONS={"dynatraceTagPropertyPath":"headers.x-dynatrace","server":"https://xyz.xyz.com" ...

To exclude quoting issues, could you paste the relevant parts of serverless.yml with the hard coded options?

Did you check if the `DT_LAMBDA_OPTIONS`environment variable is at all or only partially set in the deployed Lambda function?

**Comment by mcsmcs** [comment]
Agent options is an empty object when I hard code the credentials into the configuration file.  I've tried passing a JS object, as well as a string (below/like the documentation).  Using both methods does not set DT_LAMBDA_OPTIONS environment variable when using serverless' config.

Result: `Agent options: {}`

I'm happy to share the config outside of Github.  The set up we have is a serverless.yml file that loads in a file based on the environment:

```yml
custom: ${file(environment/${self:provider.stage}.js)}
provider:
  stage: ${env:ENV,opt:stage,'dev'} # ENV is supplied on sls deploy
```
This JS file is essentially (removed other values):

```javascript
// "environment/stage.js"
module.exports = {  
 "serverless-oneagent": {
    options: '{dynatraceTagPropertyPath: "headers.x-dynatrace", server: "https://dynatrace-nonprd.[domain.com]", tenant: "[our tenant ID]", tenanttoken: "[our tenant token]"}',
    npmModuleVersion: "1.157.186-1.0.0",
    verbose: true,
  },
}
```

When providing options via the command line the DT_LAMBDA_OPTIONS environment variable is set for the lambda.  However, I never see logs from the Agent bootstrap process.

**Comment by Hollerberg** [comment]
I found an issue reading the serverless-oneagent configuration with above setup. At the time the configuration is read, the variables in the serverless.yml file are not yet expanded. I will post a fix asap.

Beside that, your option string is not a correct JSON document. You have to quote the property names (mind "server":"https://..." vs. server:"https://..."). Otherwise, the agent will fail to parse the option string and will try to connect with localserver. Please use the string as presented in serverless deployment UI. This could be an explanation for the problems passing the options on the command line.

```Javascript
// "environment/stage.js"
module.exports = {  
 "serverless-oneagent": {
    options: '{"dynatraceTagPropertyPath": "headers.x-dynatrace", "server": "https://dynatrace-nonprd.[domain.com]", "tenant": "[our tenant ID]", "tenanttoken": "[our tenant token]"}',
    npmModuleVersion: "1.157.186-1.0.0",
    verbose: true,
  },
}
```

**Comment by Hollerberg** [comment]
I published version 1.0.6 which fixes the issue reading configuration.

**Comment by mcsmcs** [comment]
Switched to 1.0.6:

- Environment variable is set on the lambda
- I don't see the agent bootstrap logs in CloudWatch anymore
- Still no luck in Dynatrace UI

**Comment by mcsmcs** [comment]
Looks like the code is working now even with SSM providing the options.

I am getting an error when it's sending to the dynatrace environment endpoint

```
2019-01-16 21:15:42.439 UTC [b9041821] info [native] URL https://dynatrace-nonprd.domain.com/communication not working (Failed to connect to dynatrace-nonprd.domain.com port 443: Connection timed out)
2019-01-16 21:15:42.439 UTC [b9041821] info [native] Dispatcher started - using non working URL https://dynatrace-nonprd.domain.com/communication
2019-01-16 21:15:44.692 UTC [a67fb861] info [native] Exception handling periodic task protocols.messages.shared.ClusterTimeRequest: unable to perform request using https://dynatrace-nonprd.domain.com/communication: Couldn't connect to server. Totaltime: 1.5018s, Uploadsize: 0b, Downloadsize: 0b, Connecttime: 0s
```

**Comment by Hollerberg** [comment]
It seems that your ActiveGate is not reachable from public internet. On the bright side, it seems, that the issues with the serverless plugin are finally sorted out. 
Thus, I would propose to move this now to Dynatrace support (I think you guys are already in contact with Daniel K.).
